<div
class="nav flex-column nav-tabs text-center"
id="v-tabs-tab"
role="tablist"
aria-orientation="vertical"
>
<a
  class="nav-link active"
  id="v-tabs-home-tab"
  data-mdb-toggle="tab"
  href="#v-tabs-home"
  role="tab"
  aria-controls="v-tabs-home"
  aria-selected="true"
  >Home</a
>
<a
  class="nav-link"
  id="v-tabs-event-tab"
  data-mdb-toggle="tab"
  href="#v-tabs-event"
  role="tab"
  aria-controls="v-tabs-event"
  aria-selected="false"
  >Events</a
>
<a
  class="nav-link"
  id="v-tabs-messages-tab"
  data-mdb-toggle="tab"
  href="#v-tabs-messages"
  role="tab"
  aria-controls="v-tabs-messages"
  aria-selected="false"
  >Messages</a
>
</div>
